# Generated by Django 4.1.1 on 2022-12-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phoneNumber',
            field=models.CharField(default=True, max_length=64),
        ),
    ]
